# permissions for end users to edit k8sresourcecloners.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: k8sresourcecloner-editor-role
rules:
- apiGroups:
  - cache.example.org
  resources:
  - k8sresourcecloners
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cache.example.org
  resources:
  - k8sresourcecloners/status
  verbs:
  - get
