# permissions for end users to view k8sresourcecloners.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: k8sresourcecloner-viewer-role
rules:
- apiGroups:
  - cache.example.org
  resources:
  - k8sresourcecloners
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cache.example.org
  resources:
  - k8sresourcecloners/status
  verbs:
  - get
